stages:
  - lint
  - test
  - deploy


lint-backend:
  image: gradle:8.5-jdk21
  stage: lint
  script:
    - cd BoggleSpringBoot
    - ./gradlew clean pmdMain pmdTest
  artifacts:
    when: always
    paths:
      - build/reports/pmd/

test-backend:
  image: gradle:8.5-jdk21
  stage: test
  script:
    - cd BoggleSpringBoot
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - BoggleSpringBoot/build/test-results
      - BoggleSpringBoot/build/reports/tests

lint-frontend:
  image: node:20
  stage: lint
  script:
    - cd frontend
    - npm ci
    - npm run lint

test-frontend:
  image: node:20
  stage: test
  script:
    - cd frontend
    - npm ci
    - npm run test -- --run

deploy:
  stage: deploy
  tags:
    - vm-deploy
  only:
    - main
    - develop
  script:
    - cd /home/raudales-montes/Project_14
    - git fetch origin main && git checkout -f main && git pull origin main
    - docker compose -f DockerVM/docker-compose.yml down
    - docker compose -f DockerVM/docker-compose.yml build --no-cache
    - docker compose -f DockerVM/docker-compose.yml up -d
    - docker image prune -f