apiVersion: v1
kind: Secret
metadata:
  name: boggle-secret
type: Opaque
data:
  mysql_database: Ym9nZ2xl
  mysql_user: Ym9nZ2xl
  mysql_password: Ym9nZ2xl
  mysql_root_password: cm9vdF9wYXNzd29yZA==

