apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: boggle-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: boggle-secret
    creationPolicy: Owner
  data:
    - secretKey: mysql_user
      remoteRef:
        key: boggle-secrets
        property: mysql_user
    - secretKey: mysql_password
      remoteRef:
        key: boggle-secrets
        property: mysql_password
    - secretKey: mysql_database
      remoteRef:
        key: boggle-secrets
        property: mysql_database
    - secretKey: mysql_root_password
      remoteRef:
        key: boggle-secrets
        property: mysql_root_password
